### ISSUE TITLE
iOS Settings dirty dependencies

### ISSUE THREAD

**Issue by hhandika** [yako-dev/flutter-settings-ui#184]
I got dirty dependencies errors on iOS. Manually configuring SettingThemeData in the setting list does not fix the issue.

```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.1)
[✓] Connected device (3 available)
[✓] Network resources
```

```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building IOSSettingsSection(dirty, dependencies:
[SettingsTheme]):
Bad state: No element

The relevant error-causing widget was:
  IOSSettingsSection
  IOSSettingsSection:file:///Users/~/.pub-cache/hosted/pub.dev/settings_ui-2.0.2/lib/src/sections/settings_section.dart:38:16

When the exception was thrown, this was the stack:
#0      _Array.last (dart:core-patch/array.dart:56:5)
#1      IOSSettingsSection.build (package:settings_ui/src/sections/platforms/ios_settings_section.dart:23:40)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:5156:49)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5068:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5062:5)
...     Normal element mounting (47 frames)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3971:16)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3708:18)
#55     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:857:37)
#56     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:842:20)
#57     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2720:19)
#58     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:834:12)
#59     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351:23)
#60     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2506:59)
#61     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1062:15)
#62     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2506:14)
#63     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340:5)
#64     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426:5)
#65     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#67     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#68     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361:11)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#70     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#71     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1511:12)
#72     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1420:20)
#73     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#74     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#77     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#78     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#79     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#80     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#83     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#85     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#86     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#89     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#91     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#92     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#93     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#94     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#95     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#96     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:438:14)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#98     RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#101    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#102    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#103    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#104    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#105    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#107    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#108    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#109    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1056:7)
#110    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:235:7)
#111    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#113    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#116    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#118    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1449:11)
#119    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#120    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#122    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#123    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#125    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#126    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#128    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#129    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#130    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#131    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:580:43)
#132    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:607:12)
#133    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#134    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#136    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#137    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#139    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#140    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#142    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#143    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#145    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#146    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#148    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#149    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#150    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3749:14)
#151    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#152    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#153    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:122:14)
#154    RenderObject.layout (package:flutter/src/rendering/object.dart:2395:7)
#155    RenderBox.layout (package:flutter/src/rendering/box.dart:2386:11)
#156    _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:832:15)
#157    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2234:7)
#158    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1016:18)
#159    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:492:19)
#160    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:905:13)
#161    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#162    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#163    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#164    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#165    _invoke (dart:ui/hooks.dart:142:13)
#166    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#167    _drawFrame (dart:ui/hooks.dart:112:31)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by ghost** [comment]
I am seeing the same issue in Sentry

**Comment by M-ixai-L** [comment]
@hhandika @JanEnjoj Can you tell me how to reproduce this bug?

**Comment by yadaniyil** [comment]
This should be resolved in v3.0.0 — all dependencies have been updated (Flutter ≥3.16.0, Dart ≥3.5.0). Please upgrade and let us know if you still see the issue.
